ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
