ifeq ($(CONFIG_MACH_XIAOMI_MARKW),y)
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += gf_spi_markw.o platform.o netlink.o
else
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += gf_spi.o platform.o netlink.o
endif
#obj-y += gf_spi.o platform.o netlink.o
