#!/usr/bin/env bash
#
# Scripts to update latest submodules git
#
# Copyright (C) 2018 Adek Maulana
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

APP_PATH=/home/adek/kernel/stormguard

BRANCH=$(git branch | grep \* | cut -d ' ' -f2);

SB_1="$APP_PATH"/build/scripts
SB_2="$APP_PATH"/build/anykernel/miui
SB_3="$APP_PATH"/build/toolchain/gcc-linaro

echo "Working in: '$APP_PATH' branch '$BRANCH'"

git submodule sync
git submodule init
git submodule update

echo ""

cd $SB_1
branch=$(git branch | grep \* | cut -d ' ' -f2);
git checkout $branch && git pull --ff origin $branch || true
for i in $(echo $SB_1)
do
  echo "Adding $i to root repo"
  git add "$i"
done

echo ""

cd $SB_2
branch=$(git branch | grep \* | cut -d ' ' -f2);
git checkout $branch && git pull --ff origin $branch || true
for i in $(echo $SB_2)
do
  echo "Adding $i to root repo"
  git add "$i"
done

echo ""

cd $SB_3
branch=$(git branch | grep \* | cut -d ' ' -f2);
git checkout $branch && git pull --ff origin $branch || true
for i in $(echo $SB_3)
do
  echo "Adding $i to root repo"
  git add "$i"
done

echo ""

cd $APP_PATH

git commit -m "Updated remote branch of deployment repo to point latest submodules"
git push origin $BRANCH
