ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
