ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
