ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
