ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
